### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by ShereeBrown** [goldenratio/katu-aurora#1]
it not work,i was been ripping off,that Katu-aurora was work,it need update ,i dont want anymore,i am very not happy,

**Comment by goldenratio** [comment]
Thank you for reporting! Issue is fixed now.

**Comment by ShereeBrown** [comment]
there were issues,something wrong with it why keep reloads,help
![capture](https://cloud.githubusercontent.com/assets/8306345/26348516/4cf4b7e8-3ff0-11e7-820e-563eb7c82912.PNG)
